# Generated by Django 3.2 on 2021-04-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'TODO'), (1, 'DOING'), (2, 'DONE')], default=0),
        ),
    ]
