# Generated by Django 3.2 on 2021-04-08 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
