# Generated by Django 3.2 on 2021-04-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='message',
            new_name='text',
        ),
    ]
