# Generated by Django 3.2 on 2021-04-09 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
