# Generated by Django 3.2 on 2021-04-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_todo_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='meu titulo', max_length=255),
            preserve_default=False,
        ),
    ]
